services:
  - type: web
    name: oder-backend-2
    runtime: go
    buildCommand: go build -o server main.go
    startCommand: ./server
    envVars:
      - key: PORT
        value: 10000
      - key: GIN_MODE
        value: release
